-- ═══════════════════════════════════════════════════════════════════════════
-- OWNER-APPROVED DECLARATION MANIFEST · Session 110
--
-- ⛔ NOT APPLIED. ⛔ NOT PRODUCT LOGIC. ⛔ NOT A CLASSIFICATION RULE.
--
-- ⭐⭐ THIS FILE IS A RECORD OF THREE HUMAN DECISIONS, and it is deliberately
-- SEPARATE from the migration. The migration
-- (recurrence_season_key.sql) carries a generic DATA RULE that classifies rows
-- no human had to look at. These three rows are the ones that rule cannot
-- classify — that is precisely why they are here and not there.
--
-- Putting them in the migration would be pretending they were derivable. They
-- were not. Kavin looked at each one and said "lawn".
--
-- ── WHY EACH WAS APPROVED (owner's evidence, recorded, NOT generalised) ─────
-- ⛔⛔ THE EVIDENCE BELOW MUST NEVER BECOME A RULE. Quote history, quote notes
-- and programme names are NOT inputs to season resolution — that is exactly the
-- name-guessing this whole lane removed, wearing different clothes. They are
-- recorded here only so a future reader can see the decision was reasoned
-- rather than arbitrary. verify:season-recurrence fails if the reconciliation
-- report ever starts reading quotes to classify a season.
--
--   28a0b8d4-9cd0-410a-be6f-311cf99e540e  → 'lawn'
--     Service reads "Bi-weekly", which matches no keyword. Owner confirmed
--     against a live quote (EPS-2026-0116, "Recurring bi-weekly mowing.").
--
--   35a21402-3899-43dc-b103-14461cc0a84a  → 'lawn'
--     Service reads "General Upkeep" — the recurring maintenance programme.
--     Its existing end_date is already 2026-10-31, consistent with the lawn
--     season it is being declared into.
--
--   207a2e9e-6cd7-4926-8b6c-70364b5b3830  → 'lawn'
--     ⚠️ Previously mis-reported as an orphan by scripts/season-reconcile.ts:
--     the customer was read through the recurrence's JOBS, and this series has
--     none generated, so a real customer vanished behind a join. The row always
--     had customer_id 1a0ee43e-299b-41a5-8c70-bb6b3ebffd50. Owner confirmed
--     against a live quote (EPS-2026-0008, weekly mowing). Report fixed; a
--     guard now fails if any row with a customer_id cannot be named.
--
-- ── HOW S106 APPLIES THIS ──────────────────────────────────────────────────
-- AFTER the generic AUTO-SAFE backfill (migration section 3) has classified the
-- 14 rows a rule can classify. This manifest then closes the remaining three.
--
-- ⚠️ It is written to be SAFE TO RE-RUN and IMPOSSIBLE TO OVER-APPLY:
--   • each statement names one id, so it can touch nothing else;
--   • `where season_key is null` means it will not overwrite a declaration that
--     already exists — including one the owner later changes their mind about;
--   • it is scoped to the owner's own rows by RLS at execution time.
--
-- ⛔ IT DECLARES A SEASON AND NOTHING ELSE. No end_date is written and NO VISIT
-- IS TOUCHED. Sajjan's 25 future visits (12 outside the lawn season) are NOT
-- deleted or regenerated by this manifest — that is a separate, explicitly
-- approved action. See the SAJJAN note at the bottom.
-- ═══════════════════════════════════════════════════════════════════════════

set search_path to public, extensions;

update public.job_recurrences
   set season_key = 'lawn'
 where id = '28a0b8d4-9cd0-410a-be6f-311cf99e540e'
   and season_key is null;

update public.job_recurrences
   set season_key = 'lawn'
 where id = '35a21402-3899-43dc-b103-14461cc0a84a'
   and season_key is null;

update public.job_recurrences
   set season_key = 'lawn'
 where id = '207a2e9e-6cd7-4926-8b6c-70364b5b3830'
   and season_key is null;

-- ── PROOF: zero undeclared active rows ─────────────────────────────────────
-- Run this after the manifest. It must return 0. Until it does,
-- SEASON_DECLARATIONS_COMPLETE stays false and verify:season-recurrence §9
-- refuses the flip.
--
--   select count(*) as undeclared_active
--     from public.job_recurrences
--    where (season_key is null or btrim(season_key) = '')
--      and (end_date is null or end_date >= current_date);
--
-- And the full picture, which should show 17 declared rows:
--
--   select season_key, count(*)
--     from public.job_recurrences
--    where end_date is null or end_date >= current_date
--    group by season_key order by 2 desc;

-- ── ⛔ SAJJAN'S EXISTING VISITS — NOT AUTHORISED BY THIS FILE ───────────────
-- Declaring the season does NOT authorise touching a visit. As measured:
--   • 25 future generated visits, 2026-09-05 → 2027-07-31
--   • 12 of them fall outside the lawn season once declared
--   • 12 are removable under Session 39's rule (scheduled, uninvoiced,
--     non-anchor, strictly past the end); the rest are protected
--
-- Three actions remain open, and ALL THREE require Kavin's explicit approval of
-- the visit mutation itself:
--   Keep        — declare the season, leave every visit where it is
--   Remove      — set end_date, remove only the removable visits
--   Regenerate  — set end_date, then re-plan within the declared season
--
-- ⭐ The owner's stated PREFERENCE is REGENERATE WITHIN SEASON, because this is
-- genuine recurring mowing and generated winter visits should not be preserved.
-- ⛔ A stated preference is NOT production-write approval. Nothing is removed or
-- regenerated until Kavin approves that specific mutation.
--
-- Sarah Brown: no cleanup expected — her future visits already sit inside the
-- declared lawn window (end_date 2026-10-31).
-- Nicole Blackburn: no cleanup possible — the series has no generated visits.
