-- Portal property identity — ADDITIVE change to get_portal_data.
--
-- WHY. The portal card said "Priced for your measured 10,369 sq ft" on every quote a
-- customer had, because this RPC returned exactly ONE property ('property', limit 1)
-- and the quotes projection carried no property_id at all. A real landlord (6 quotes,
-- 6 properties, 407–10,369 sq ft) saw her PRIMARY property's area on all six cards —
-- the $40 quote for a 407 sq ft lawn claimed 10,369, a 25x overstatement, printed
-- under "What's behind this price" with a green check, on live `sent` quotes. There was
-- no client-side fix available: the other five properties' areas were not in the
-- payload in any form.
--
-- WHAT CHANGED — three ADDITIONS, nothing removed, nothing re-ordered:
--   1. quotes   += property_id   (the canonical FK; the card can now resolve its own property)
--   2. invoices += property_id   (same, and it unblocks per-property invoice grouping)
--   3. 'properties' = the full array, NEW key
--
-- WHAT DELIBERATELY DID NOT CHANGE: 'property' (singular) stays byte-identical —
-- same columns, same `is_primary desc nulls last, created_at asc limit 1` ordering.
-- Several surfaces read it (Home "Your property", PropertyTab, invoice/receipt PDF
-- fallback). Replacing it with the array would have been the same edit twice; leaving
-- it means every existing reader is untouched and this migration cannot regress them.
--
-- This definition was pulled LIVE via pg_get_functiondef immediately before editing
-- (4830 chars) and extended in place. It was NOT reconstructed from an older file:
-- re-running a stale copy of this function is a known production regression here, and
-- a shrinking definition length is the signature of exactly that mistake.
-- Expected: length grows. Verify after applying.

-- ══════════════════════════════════════════════════════════════════════════
-- ⚠️  SUPERSEDED — DO NOT RESTORE THIS BODY.  (INF-2, 2026-07-17)
--
--   get_portal_data now has exactly ONE definition:
--       supabase/CANONICAL-get_portal_data.sql
--
--   A complete copy of the CURRENT body stood here. It was correct — and that
--   was the problem: a second full copy is a second thing to keep in sync, and
--   the next edit would have had two places to land. The body moved verbatim
--   into the canonical file; nothing about it changed.
--
--   Everything else in this file is UNCHANGED and still safe to run.
-- ══════════════════════════════════════════════════════════════════════════
