-- ════════════════════════════════════════════════════════════
-- MIGRATION 2026-07-14 — Portal service plans (feed the real engine)
--
-- The portal was INFERRING a customer's recurring plan from their upcoming jobs:
--   activeRecIds = upcoming.map(j => j.recurrence_id)
-- so the moment a series' scheduled horizon ran out, the plan silently vanished
-- from the portal — a customer on an active weekly plan was shown nothing at all.
-- It also hand-rolled a weaker version of logic the owner's customer page already
-- has in lib/recurrence.buildServicePlans (cadence, weekday, season window, next
-- visit, remaining, paused, initial-vs-recurring price).
--
-- This projects the fields that engine needs, so the portal can run the SAME
-- function the owner's screens run — customer and owner can no longer disagree
-- about a plan, and an exhausted series reports "paused" truthfully instead of
-- disappearing.
--
-- Recreates get_portal_data with ONLY additive fields (identical to the
-- 2026-07-09 definition otherwise). Idempotent — safe to run more than once.
-- ════════════════════════════════════════════════════════════

-- ══════════════════════════════════════════════════════════════════════════
-- ⚠️  SUPERSEDED — DO NOT RESTORE THIS BODY.  (INF-2, 2026-07-17)
--
--   get_portal_data now has exactly ONE definition:
--       supabase/CANONICAL-get_portal_data.sql
--
--   A complete, runnable OLDER copy stood here. Running this file replaced the
--   live function with it — silently, with no error — dropping
--   the `services` and `properties` keys.
--   Nothing failed; the portal just started returning less. That is why the
--   body is gone rather than merely commented "outdated".
--
--   Everything else in this file is UNCHANGED and still safe to run.
-- ══════════════════════════════════════════════════════════════════════════
grant execute on function public.get_portal_data(text) to anon, authenticated;
