-- ══════════════════════════════════════════════════════════════════════════════
-- Portal: offer the company's OWN services, not a hardcoded lawn menu.
--
-- APPLIED + VERIFIED IN PROD 2026-07-15 (executed against real tokens, not just
-- inspected). This file is the repo's record of what ran — there is no migration
-- ledger in this project.
--
-- WHY: the portal's "Request a service" tab shipped a fixed list — Mulch, Spring
-- Cleanup, Fall Cleanup, Weed Control, Landscaping. A pool company's customers
-- were offered lawn work their company doesn't sell, and could never request the
-- work it does. service_templates is ALREADY the owner's industry-neutral
-- catalogue (name, category, default_rate, pricing_display_type), so this exposes
-- it and ONE portal adapts to whatever the business offers. No new table, no
-- second portal, no industry flag.
--
-- ⚠️ READ BEFORE EDITING get_portal_data ⚠️
-- This function is create-or-replace'd by SEVEN files now. This body was taken
-- from the LIVE function (pg_get_functiondef) immediately before writing, NOT from
-- a repo file — each older file in the chain silently rolls the portal backward.
-- It preserves valid_until, etransfer_email, quote_services, discounts, gst_number
-- and service_seasons. Verify a change by EXECUTING it on a token whose customer
-- has quotes; the text looking right is not evidence.
--
-- (History: the first attempt at this shipped `json_agg(s order by s.sort_order)`
-- where the inline subquery didn't select sort_order → 42703 for EVERY customer,
-- i.e. the whole portal down, not just the new key. Caught by executing it. That
-- is why sort_order is selected below.)
--
-- Additive: clients that don't read `services` are unaffected.
-- ══════════════════════════════════════════════════════════════════════════════
-- ══════════════════════════════════════════════════════════════════════════
-- ⚠️  SUPERSEDED — DO NOT RESTORE THIS BODY.  (INF-2, 2026-07-17)
--
--   get_portal_data now has exactly ONE definition:
--       supabase/CANONICAL-get_portal_data.sql
--
--   A complete, runnable OLDER copy stood here. Running this file replaced the
--   live function with it — silently, with no error — dropping
--   the `properties` key.
--   Nothing failed; the portal just started returning less. That is why the
--   body is gone rather than merely commented "outdated".
--
--   Everything else in this file is UNCHANGED and still safe to run.
-- ══════════════════════════════════════════════════════════════════════════
