-- ═══════════════════════════════════════════════════════════════════════════
-- ARCHIVED MIGRATION — HISTORY ONLY. DO NOT RE-RUN.
--
--   version : 20260716232854
--   name    : wage_history_deterministic_ordering
--
-- Recovered 2026-08-14 from supabase_migrations.schema_migrations — the SQL
-- production actually executed, not a repo file believed to match it.
--
-- Its effects are already folded into supabase/migrations/*_baseline.sql. This
-- copy exists so "why is this column here?" is answerable, and for nothing else.
-- Re-running one replaces a live object with an older body — silently, no error.
-- ═══════════════════════════════════════════════════════════════════════════

-- An audit trail's ORDER is load-bearing — "what was the wage progression" is
-- unanswerable if two rows tie. Two problems, both fixed here:
--
--  1. now() returns TRANSACTION START time, so every wage_history row written in
--     one transaction (e.g. a technician created WITH a wage and raised by the
--     same import) gets a byte-identical created_at. Proven by execution:
--     `select now() = now()` is TRUE. clock_timestamp() is the real wall clock at
--     statement time, which is what an audit event actually means.
--
--  2. Even clock_timestamp() can tie at microsecond resolution. `seq` is a
--     monotonic tiebreaker, making the ordering provably total rather than
--     merely usually-right. Order by (seq) — never by created_at alone.
alter table public.wage_history
  alter column created_at set default clock_timestamp();

alter table public.wage_history
  add column if not exists seq bigint generated by default as identity;

comment on column public.wage_history.created_at is
  'clock_timestamp() (real wall clock), NOT now() — now() is transaction start and ties every row written in one transaction.';
comment on column public.wage_history.seq is
  'Monotonic tiebreaker. ORDER BY seq for a provably total audit order; created_at can tie at microsecond resolution.';

create index if not exists wage_history_tech_seq_idx on public.wage_history (technician_id, seq desc);