-- ═══════════════════════════════════════════════════════════════════════════
-- ARCHIVED MIGRATION — HISTORY ONLY. DO NOT RE-RUN.
--
--   version : 20260717061245
--   name    : measurement_engine_v2_history
--
-- Recovered 2026-08-14 from supabase_migrations.schema_migrations — the SQL
-- production actually executed, not a repo file believed to match it.
--
-- Its effects are already folded into supabase/migrations/*_baseline.sql. This
-- copy exists so "why is this column here?" is answerable, and for nothing else.
-- Re-running one replaces a live object with an older body — silently, no error.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── Measurement history ──────────────────────────────────────────────────────
-- Append-only log of every version of every measurement, per kind.
--
-- WHY NOT THE EXISTING TABLES
--  * `measurements` is the auto-vs-accepted ACCURACY log (auto_sqft,
--    accepted_sqft, diff_pct) that trains the per-neighbourhood ratio. It answers
--    "how good is our estimator", is lawn/ft²-only, and must keep doing exactly
--    that.
--  * `properties.measurement_history` is a jsonb array of lawn snapshots carrying
--    a pricing recommendation inside it. It is lawn-shaped and coupled to pricing.
-- Neither can answer "what did this property's FENCE measure last month". This can.
--
-- WRITTEN BY A TRIGGER, not by app code: history that a caller can forget to
-- write is not history. One writer (property_measurements) produces both the
-- current row and its own audit trail.
create table if not exists public.property_measurement_events (
  id uuid primary key default gen_random_uuid(),
  -- clock_timestamp(), not now(): now() is transaction-start, so two saves in one
  -- transaction would tie and the order of history would be ambiguous. Same trap
  -- already hit (and fixed) on wage_history.
  created_at timestamptz not null default clock_timestamp(),
  seq bigint generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  measurement_id uuid,
  kind text not null,
  unit text not null,
  value numeric(12,2) not null,
  shapes jsonb not null default '[]'::jsonb,
  source text not null,
  confidence text not null,
  confidence_reason text not null,
  -- 'measured' = created/updated · 'removed' = deleted. A deletion IS history.
  action text not null,
  measured_at timestamptz not null,
  constraint property_measurement_events_kind_known
    check (kind in ('lawn','mulch','gravel','rock','concrete','fencing','hedges','trees','snow')),
  constraint property_measurement_events_action_known check (action in ('measured','removed')),
  constraint property_measurement_events_value_nonneg check (value >= 0)
);

create index if not exists pme_property_idx on public.property_measurement_events (property_id, seq desc);
create index if not exists pme_property_kind_idx on public.property_measurement_events (property_id, kind, seq desc);
create index if not exists pme_user_idx on public.property_measurement_events (user_id, seq desc);

comment on column public.property_measurement_events.seq is
  'Monotonic tiebreaker. ORDER BY seq — created_at can tie at microsecond resolution.';

create or replace function public.log_measurement_event() returns trigger
language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    insert into public.property_measurement_events
      (user_id, property_id, measurement_id, kind, unit, value, shapes, source, confidence, confidence_reason, action, measured_at)
    values (old.user_id, old.property_id, old.id, old.kind, old.unit, old.value, old.shapes,
            old.source, old.confidence, old.confidence_reason, 'removed', old.measured_at);
    return null;
  end if;
  -- Only log when something a reader would care about actually moved. An
  -- unchanged re-save is not a measurement event.
  if tg_op = 'UPDATE'
     and new.value is not distinct from old.value
     and new.source is not distinct from old.source
     and new.shapes is not distinct from old.shapes then
    return null;
  end if;
  insert into public.property_measurement_events
    (user_id, property_id, measurement_id, kind, unit, value, shapes, source, confidence, confidence_reason, action, measured_at)
  values (new.user_id, new.property_id, new.id, new.kind, new.unit, new.value, new.shapes,
          new.source, new.confidence, new.confidence_reason, 'measured', new.measured_at);
  return null;
end $$;

drop trigger if exists property_measurements_history on public.property_measurements;
create trigger property_measurements_history
  after insert or update or delete on public.property_measurements
  for each row execute function public.log_measurement_event();

alter table public.property_measurement_events enable row level security;
drop policy if exists pme_select on public.property_measurement_events;
drop policy if exists pme_insert on public.property_measurement_events;
-- SELECT + INSERT only, deliberately: history is append-only. No update/delete
-- policy means a rewritten past is not merely discouraged, it is impossible.
create policy pme_select on public.property_measurement_events for select using (auth.uid() = user_id);
create policy pme_insert on public.property_measurement_events for insert with check (auth.uid() = user_id);

comment on table public.property_measurement_events is
  'Append-only history for property_measurements, written by trigger. No UPDATE/DELETE policy — history cannot be rewritten. Distinct from `measurements` (the lawn auto-vs-accepted accuracy log that trains neighbourhood ratios).';