import type { TradePack } from './types'

// ── Starter catalogues for the named trades ──────────────────────────────────
// PURE SEED DATA: each pack is what a brand-new business of that trade gets
// offered at setup — 9-12 services with Canadian 2026 rates and the pricing
// mode that trade actually quotes in. Owners edit or delete every row; nothing
// here is read after seeding, and nothing here is read by any engine, ever
// (scripts/verify-trades.ts enforces both).
//
// Provenance: drafted and adversarially reviewed per-trade (a skeptical-owner
// pass corrected pricing modes, cut services a small shop wouldn't self-perform,
// added missing bread-and-butter work), then cross-reviewed for registry-wide
// consistency. Category names deliberately reuse one small vocabulary
// (Repairs / Installations / Maintenance / Inspections) across trades.
//
// No seasons here yet — ServiceSeasons is still the closed {lawn, snow} shape
// until the seasons engine generalizes (Phase 3); inventing season dates for a
// trade is the owner's call, not ours. seasonalCampaigns: [] = the campaign
// studio falls back to the neutral pack's presets.

export const CATALOG_PACKS: TradePack[] = [
  {
    key: "cleaning",
    label: "Cleaning",
    blurb: "Homes, rentals and offices — recurring and one-time cleans.",
    services: [
      { name: "Standard House Cleaning", category: "Home Cleaning", default_rate: 55, pricing_display_type: "hourly",
        default_description: "Kitchen, bathrooms, floors, dusting and all living areas. Hourly rate per cleaner; most homes take 2 to 4 hours." },
      { name: "Recurring Home Cleaning", category: "Home Cleaning", default_rate: 135, pricing_display_type: "starting_from",
        default_description: "Scheduled weekly or bi-weekly clean: kitchen, bathrooms, floors and dusting every visit. Priced by home size and frequency." },
      { name: "Deep Cleaning", category: "Deep & Move-Out", default_rate: 320, pricing_display_type: "starting_from",
        default_description: "Top-to-bottom clean: baseboards, cabinet fronts, light fixtures, vents, tile and detailed hand dusting. Recommended before starting recurring service." },
      { name: "Move-In / Move-Out Cleaning", category: "Deep & Move-Out", default_rate: 380, pricing_display_type: "starting_from",
        default_description: "Empty-home clean: inside cupboards, closets and appliances, baseboards, windowsills and floors. Ready for final inspection and key handover." },
      { name: "Airbnb & Rental Turnover", category: "Commercial & Rentals", default_rate: 110, pricing_display_type: "starting_from",
        default_description: "Full reset between guests: beds made, bathrooms and kitchen cleaned, floors done, supplies restocked, photo check on the way out." },
      { name: "Office & Retail Cleaning", category: "Commercial & Rentals", default_rate: 130, pricing_display_type: "starting_from",
        default_description: "After-hours cleaning for offices and small storefronts: floors, washrooms, kitchenettes, garbage and touch points. Flat price per visit after a walkthrough." },
      { name: "Post-Renovation Cleaning", category: "Specialty", default_rate: 65, pricing_display_type: "hourly",
        default_description: "Fine dust removal after construction: walls, vents, fixtures, floors and interior glass. Billed hourly because dust levels vary job to job." },
      { name: "Interior Window Cleaning", category: "Specialty", default_rate: 140, pricing_display_type: "starting_from",
        default_description: "Inside glass, sills and tracks throughout the home. Ground-level exterior panes can be added on request." },
      { name: "Oven & Fridge Deep Clean", category: "Specialty", default_rate: 90, pricing_display_type: "starting_from",
        default_description: "Inside of oven and fridge scrubbed and degreased. Book with any cleaning or on its own." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "electrical",
    label: "Electrical",
    blurb: "Troubleshooting, fixtures, panels and EV chargers.",
    services: [
      { name: "Electrical Service Call", category: "Repairs", default_rate: 125, pricing_display_type: "hourly_materials",
        default_description: "Troubleshooting and repair for dead outlets, tripping breakers and flickering lights. One licensed electrician; common parts stocked on the truck." },
      { name: "Light Fixture Replacement", category: "Installations", default_rate: 145, pricing_display_type: "starting_from",
        default_description: "Swap an existing fixture for one you supply, up to standard ceiling height. Vaulted ceilings or new boxes quoted on site." },
      { name: "New Outlet or Circuit", category: "Panels & Wiring", default_rate: 280, pricing_display_type: "starting_from",
        default_description: "New receptacle or dedicated circuit, fished through finished walls where possible. GFCI or AFCI protection included where code requires it." },
      { name: "Pot Light Installation", category: "Installations", default_rate: 175, pricing_display_type: "starting_from",
        default_description: "Per-light price for installation into an existing ceiling; multi-light pricing quoted on site." },
      { name: "Ceiling Fan Installation", category: "Installations", default_rate: 260, pricing_display_type: "starting_from",
        default_description: "Fan-rated box, assembly and mounting for a customer-supplied fan on ceilings up to 10 ft. Wall or remote control wiring included." },
      { name: "Panel Upgrade (100A to 200A)", category: "Panels & Wiring", default_rate: 3200, pricing_display_type: "starting_from",
        default_description: "Full 200 amp panel replacement with new breakers, permit and utility disconnect coordination. Final price depends on mast and grounding condition." },
      { name: "EV Charger Installation", category: "Installations", default_rate: 900, pricing_display_type: "starting_from_materials",
        default_description: "Level 2 charger circuit from your panel to garage or driveway, permit and load calculation included. Charger and wire billed as materials." },
      { name: "Electrical Safety Inspection", category: "Inspections", default_rate: 250, pricing_display_type: "starting_from",
        default_description: "Room-by-room check of panel, grounding, GFCIs and alarms with a written report. Useful for home purchases, insurance renewals and older homes." },
      { name: "Smoke & CO Alarm Replacement", category: "Inspections", default_rate: 150, pricing_display_type: "starting_from",
        default_description: "Hardwired smoke and carbon monoxide alarm replacement, interconnect tested. Price covers the first unit; extras on the same visit cost less." },
      { name: "Aluminum Wiring Pigtailing", category: "Panels & Wiring", default_rate: 1500, pricing_display_type: "starting_from",
        default_description: "Copper pigtails on aluminum connections with CSA-approved connectors; permit and inspection paperwork for your insurer. Priced per device after a walkthrough." },
      { name: "Hot Tub Wiring", category: "Installations", default_rate: 850, pricing_display_type: "starting_from_materials",
        default_description: "Dedicated GFCI-protected circuit and outdoor disconnect for a hot tub or swim spa, permit included. Breaker, wire and disconnect billed as materials." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "handyman",
    label: "Handyman",
    blurb: "Small repairs and to-do lists, done right.",
    services: [
      { name: "General Handyman Service", category: "General", default_rate: 95, pricing_display_type: "hourly_materials",
        default_description: "To-do lists and small fixes around the house. One-hour minimum, then billed in half-hour blocks. Parts and materials at cost." },
      { name: "Drywall Repair & Patching", category: "Repairs", default_rate: 175, pricing_display_type: "starting_from_materials",
        default_description: "Patch holes and cracks, tape, mud, and sand smooth, ready for paint. Larger wall sections quoted after photos or a site visit." },
      { name: "Door Repair & Adjustment", category: "Repairs", default_rate: 135, pricing_display_type: "starting_from_materials",
        default_description: "Fix sticking or sagging doors, replace hinges, handles, latches, and weatherstripping. Covers interior and exterior doors." },
      { name: "Faucet & Toilet Repair", category: "Repairs", default_rate: 165, pricing_display_type: "starting_from_materials",
        default_description: "Replace a customer-supplied faucet, fix running toilets, and stop drips under the sink. Anything behind the wall goes to a plumber." },
      { name: "Deck & Fence Repair", category: "Repairs", default_rate: 225, pricing_display_type: "starting_from_materials",
        default_description: "Replace loose or rotten boards, re-secure railings and gates. Full rebuilds and new posts quoted separately." },
      { name: "TV Wall Mounting", category: "Installations", default_rate: 149, pricing_display_type: "starting_from",
        default_description: "Secure mount into studs, levelled, with cables tidied. Covers TVs up to 65 inches on drywall; brick or over-fireplace quoted ahead." },
      { name: "Light Fixture & Ceiling Fan Swap", category: "Installations", default_rate: 145, pricing_display_type: "starting_from",
        default_description: "Like-for-like swap on existing wiring, fixture supplied by you. New circuits or panel work need a licensed electrician." },
      { name: "Furniture & Flat-Pack Assembly", category: "Installations", default_rate: 85, pricing_display_type: "hourly",
        default_description: "Assembly of flat-pack furniture, shelving, and playsets. Tall units are anchored to the wall for safety." },
      { name: "Baseboard & Trim Installation", category: "Installations", default_rate: 8, pricing_display_type: "per_linear_ft",
        default_description: "Supply and install primed MDF baseboard or quarter round, mitred corners, nail holes filled. Painting not included." },
      { name: "Caulking & Sealing", category: "Maintenance", default_rate: 150, pricing_display_type: "starting_from",
        default_description: "Strip old caulk and reseal tubs, showers, or kitchen counters with mould-resistant silicone. Price covers one bathroom or kitchen." },
      { name: "Gutter Cleaning", category: "Maintenance", default_rate: 180, pricing_display_type: "starting_from",
        default_description: "Clear and bag debris, flush downspouts, and check for loose hangers. Price covers a single-storey home; two-storey quoted ahead." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "hvac",
    label: "HVAC",
    blurb: "Furnaces, ACs and air quality — service and installs.",
    services: [
      { name: "Furnace Repair", category: "Repairs", default_rate: 189, pricing_display_type: "starting_from_materials",
        default_description: "Diagnosis and repair of gas or electric furnaces. Covers the service call and first hour on site; parts quoted before we replace anything." },
      { name: "Air Conditioner Repair", category: "Repairs", default_rate: 189, pricing_display_type: "starting_from_materials",
        default_description: "Central AC diagnosis and repair, including electrical and refrigerant checks. Parts and refrigerant quoted before work starts." },
      { name: "Furnace Tune-Up", category: "Maintenance", default_rate: 169, pricing_display_type: "starting_from",
        default_description: "Annual fall service: burner and blower cleaning, heat exchanger inspection, new filter, carbon monoxide and safety checks." },
      { name: "Air Conditioner Tune-Up", category: "Maintenance", default_rate: 149, pricing_display_type: "starting_from",
        default_description: "Spring service: condenser coil cleaning, refrigerant pressure check, condensate drain flush, and electrical inspection." },
      { name: "High-Efficiency Furnace Installation", category: "Installations", default_rate: 5995, pricing_display_type: "starting_from",
        default_description: "Supply and install a high-efficiency gas furnace, including removal of the old unit, venting, permit, and startup." },
      { name: "Central Air Conditioner Installation", category: "Installations", default_rate: 5495, pricing_display_type: "starting_from",
        default_description: "Supply and install a new central AC sized to your home. Includes pad, line set, electrical hookup, and commissioning." },
      { name: "Cold-Climate Heat Pump Installation", category: "Installations", default_rate: 9995, pricing_display_type: "starting_from",
        default_description: "Supply and install a cold-climate heat pump. We size the system, handle rebate paperwork, and commission it before we leave." },
      { name: "Ductless Mini-Split Installation", category: "Installations", default_rate: 4295, pricing_display_type: "starting_from",
        default_description: "Single-zone ductless heat pump, supplied and installed. Good for additions, garages, and homes without ducts. Extra zones quoted separately." },
      { name: "Water Heater Replacement", category: "Installations", default_rate: 2295, pricing_display_type: "starting_from",
        default_description: "Swap out a gas or electric tank water heater, including haul-away of the old tank and any code-required venting updates." },
      { name: "Smart Thermostat Installation", category: "Installations", default_rate: 329, pricing_display_type: "starting_from",
        default_description: "Supply and install a smart thermostat, wired, connected to Wi-Fi, and set up on your phone. Install-only pricing if you already have the unit." },
      { name: "Ductwork Repair & Modification", category: "Repairs", default_rate: 125, pricing_display_type: "hourly_materials",
        default_description: "Sheet metal repairs, new runs, and transitions for renovations or equipment changes. Billed hourly plus materials." },
      { name: "HRV / Air Exchanger Service", category: "Maintenance", default_rate: 249, pricing_display_type: "starting_from",
        default_description: "Full service of your heat recovery ventilator: core wash, new filters, condensate line check, and airflow balancing." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "junk_removal",
    label: "Junk Removal",
    blurb: "Single items to full cleanouts, hauled and disposed.",
    services: [
      { name: "Single Item Pickup", category: "Single Items", default_rate: 119, pricing_display_type: "starting_from",
        default_description: "One item picked up from anywhere on the property — curb, garage, or basement. Loading, hauling and disposal fees included." },
      { name: "Furniture Removal", category: "Single Items", default_rate: 129, pricing_display_type: "starting_from",
        default_description: "Couches, tables, dressers and other furniture carried out from wherever it sits. We donate pieces that are still usable." },
      { name: "Appliance Removal", category: "Single Items", default_rate: 139, pricing_display_type: "starting_from",
        default_description: "Fridges, freezers, washers, dryers and stoves. Freon units handled properly and dropped at a certified recycler." },
      { name: "Mattress & Box Spring Removal", category: "Single Items", default_rate: 129, pricing_display_type: "starting_from",
        default_description: "Mattresses and box springs hauled away for recycling. Disposal and recycling fees included in the price." },
      { name: "Quarter Truck Load", category: "Truck Loads", default_rate: 249, pricing_display_type: "starting_from",
        default_description: "About a level pickup-truck bed of mixed junk. Two-person crew loads it, sweeps up and hauls it away. Disposal included." },
      { name: "Half Truck Load", category: "Truck Loads", default_rate: 399, pricing_display_type: "starting_from",
        default_description: "Roughly what a one-bedroom cleanout produces. Loading, hauling, disposal and donation drop-offs included." },
      { name: "Full Truck Load", category: "Truck Loads", default_rate: 649, pricing_display_type: "starting_from",
        default_description: "Our biggest single load, about 15 cubic yards of mixed junk. Loading, hauling and all dump fees included." },
      { name: "Garage Cleanout", category: "Cleanouts", default_rate: 349, pricing_display_type: "starting_from",
        default_description: "Full clear-out of a single or double garage. We sort for donation, load everything and sweep the floor before we leave." },
      { name: "Estate & Whole-Home Cleanout", category: "Cleanouts", default_rate: 999, pricing_display_type: "starting_from",
        default_description: "Whole-home clear-outs for estates, moves and rental turnovers. Sorted for donation and recycling where possible. Final price set after a walkthrough." },
      { name: "Construction Debris Removal", category: "Specialty", default_rate: 299, pricing_display_type: "starting_from",
        default_description: "Renovation debris like drywall, lumber, flooring and fixtures. Priced by volume and weight; heavy-material rates confirmed on site." },
      { name: "Hot Tub Removal", category: "Specialty", default_rate: 549, pricing_display_type: "starting_from",
        default_description: "We cut the tub up, haul it out and dispose of the shell and skirt. Must be drained and disconnected before we arrive." },
      { name: "Shed Teardown & Removal", category: "Specialty", default_rate: 449, pricing_display_type: "starting_from",
        default_description: "Teardown and haul-away of wood or metal sheds up to 10x10. Site left broom-clean; concrete pads not included." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "painting",
    label: "Painting",
    blurb: "Interior and exterior painting, prep to final coat.",
    services: [
      { name: "Interior Room Painting", category: "Interior", default_rate: 450, pricing_display_type: "starting_from",
        default_description: "Two coats on the walls of one standard room. Includes minor hole filling, cutting in, floor protection and cleanup." },
      { name: "Whole Home Interior Repaint", category: "Interior", default_rate: 3800, pricing_display_type: "starting_from",
        default_description: "Walls throughout the home, two coats. Ceilings and trim quoted separately. Includes prep, masking and daily cleanup." },
      { name: "Ceiling Painting", category: "Interior", default_rate: 250, pricing_display_type: "starting_from",
        default_description: "Flat white ceiling paint, one room, two coats. Includes light stain blocking and full masking of walls and floors." },
      { name: "Trim & Baseboard Painting", category: "Interior", default_rate: 3.5, pricing_display_type: "per_linear_ft",
        default_description: "Baseboards, casings and window trim in durable semi-gloss. Includes light sanding, caulking of gaps and two coats." },
      { name: "Exterior House Painting", category: "Exterior", default_rate: 4500, pricing_display_type: "starting_from",
        default_description: "Siding, soffit, fascia and trim, two coats of exterior acrylic. Includes power wash, scraping, spot priming and caulking." },
      { name: "Deck & Fence Staining", category: "Exterior", default_rate: 3.25, pricing_display_type: "per_sqft",
        default_description: "Clean, brighten and stain with a penetrating or solid stain. Standard prep included; board replacement extra." },
      { name: "Cabinet Painting", category: "Specialty", default_rate: 2800, pricing_display_type: "starting_from",
        default_description: "Cabinet doors, drawers and frames sprayed for a factory-smooth finish. Includes degrease, sand, prime and two topcoats." },
      { name: "Drywall Repair & Patching", category: "Repairs & Prep", default_rate: 85, pricing_display_type: "hourly_materials",
        default_description: "Patch holes and cracks, then tape, mud and sand to paint-ready. Repainting of the repaired area quoted separately." },
      { name: "Wallpaper Removal", category: "Repairs & Prep", default_rate: 75, pricing_display_type: "hourly",
        default_description: "Strip paper and backing, wash off adhesive and repair minor wall damage. Walls left ready to prime and paint." },
      { name: "Popcorn Ceiling Removal", category: "Specialty", default_rate: 4.5, pricing_display_type: "per_sqft",
        default_description: "Scrape texture, skim coat, sand and prime to a smooth, paint-ready ceiling. Room is fully sealed off during the work." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "pest_control",
    label: "Pest Control",
    blurb: "Inspections, treatments and prevention plans.",
    services: [
      { name: "Home Pest Inspection", category: "Inspections", default_rate: 150, pricing_display_type: "starting_from",
        default_description: "Full interior and exterior inspection. Written report covering what we found, likely entry points, and a treatment plan with pricing." },
      { name: "Exterior Perimeter Spray", category: "Treatments", default_rate: 195, pricing_display_type: "starting_from",
        default_description: "Residual barrier spray around the foundation, doors, and windows for ants, spiders, and earwigs. Free re-treat if activity returns within 90 days." },
      { name: "Ant Treatment", category: "Treatments", default_rate: 275, pricing_display_type: "starting_from",
        default_description: "Interior and exterior treatment for pavement and household ants. Includes one follow-up visit if activity continues after three weeks." },
      { name: "Carpenter Ant Treatment", category: "Treatments", default_rate: 395, pricing_display_type: "starting_from",
        default_description: "We locate the nest, treat wall voids and exterior trails, and warranty the work for six months. Follow-up visit included." },
      { name: "Wasp & Hornet Nest Removal", category: "Treatments", default_rate: 175, pricing_display_type: "starting_from",
        default_description: "Removal or treatment of accessible nests on the house, deck, or trees. We come back at no charge if the nest is still active a week later." },
      { name: "Cockroach Treatment", category: "Treatments", default_rate: 375, pricing_display_type: "starting_from",
        default_description: "Gel bait and residual treatment of kitchen and bathrooms. Two visits, three weeks apart. Prep sheet provided before we start." },
      { name: "Bed Bug Treatment", category: "Treatments", default_rate: 650, pricing_display_type: "starting_from",
        default_description: "Two chemical treatments per affected room, two to three weeks apart. Includes a prep checklist and mattress encasement recommendations." },
      { name: "Flea Treatment", category: "Treatments", default_rate: 350, pricing_display_type: "starting_from",
        default_description: "Interior treatment for fleas on all floors, baseboards, and pet rest areas. Two visits, two weeks apart. Prep and vacuuming checklist provided." },
      { name: "Mouse & Rat Control", category: "Rodents & Wildlife", default_rate: 325, pricing_display_type: "starting_from",
        default_description: "Inspection, interior traps, and tamper-proof exterior bait stations. Includes two follow-up visits to check and re-bait." },
      { name: "Mouse-Proofing & Entry Sealing", category: "Rodents & Wildlife", default_rate: 250, pricing_display_type: "starting_from_materials",
        default_description: "Sealing entry points with steel mesh and sealant after inspection: weep vents, utility line gaps, garage door sweeps, foundation cracks." },
      { name: "Squirrel Removal", category: "Rodents & Wildlife", default_rate: 425, pricing_display_type: "starting_from",
        default_description: "One-way door installed over the entry point so squirrels leave and can't return. Main entry sealed once they're out." },
      { name: "Seasonal Home Protection Plan", category: "Protection Plans", default_rate: 549, pricing_display_type: "starting_from",
        default_description: "Three scheduled visits a year (spring, summer, fall) covering ants, spiders, wasps, and mice. Free callbacks between visits." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "plumbing",
    label: "Plumbing",
    blurb: "Service calls, drains, fixtures and water heaters.",
    services: [
      { name: "Plumbing Service Call", category: "Repairs", default_rate: 145, pricing_display_type: "hourly_materials",
        default_description: "Licensed plumber for leaks, running toilets, low pressure and general repairs. One-hour minimum; parts billed separately." },
      { name: "Drain Cleaning", category: "Drains & Sewer", default_rate: 249, pricing_display_type: "starting_from",
        default_description: "Clear a clogged sink, tub, shower or toilet drain by auger. Price covers one drain; we test flow before we leave." },
      { name: "Toilet Repair", category: "Repairs", default_rate: 165, pricing_display_type: "starting_from",
        default_description: "Fix a running, leaking or weak-flushing toilet. Covers common parts like flappers, fill valves and supply lines." },
      { name: "Faucet Installation", category: "Installations", default_rate: 225, pricing_display_type: "starting_from_materials",
        default_description: "Swap out a kitchen or bathroom faucet, including new supply lines and a shutoff check. Faucet billed separately or bring your own." },
      { name: "Toilet Installation", category: "Installations", default_rate: 295, pricing_display_type: "starting_from_materials",
        default_description: "Remove the old toilet and install a new one with a new wax seal and supply line. Toilet billed separately or supplied by you." },
      { name: "Garburator Installation", category: "Installations", default_rate: 265, pricing_display_type: "starting_from_materials",
        default_description: "Install or replace an under-sink garburator (garbage disposal), with new drain connections leak-tested. Unit billed separately or supplied by you." },
      { name: "Water Heater Replacement", category: "Installations", default_rate: 2350, pricing_display_type: "starting_from",
        default_description: "Supply and install a standard 40-gallon gas tank, including haul-away of the old unit and code-required fittings." },
      { name: "Sump Pump Replacement", category: "Installations", default_rate: 795, pricing_display_type: "starting_from",
        default_description: "Replace a failed sump pump with a new 1/3 HP unit and check valve, tested under load before we leave." },
      { name: "Main Sewer Line Cleaning", category: "Drains & Sewer", default_rate: 395, pricing_display_type: "starting_from",
        default_description: "Power auger the main line from the cleanout to the street to clear roots and buildup. Camera check available after clearing." },
      { name: "Sewer Camera Inspection", category: "Drains & Sewer", default_rate: 295, pricing_display_type: "starting_from",
        default_description: "Camera the line to find the blockage or break. Includes recorded video and a located dig spot if a repair is needed." },
      { name: "Emergency After-Hours Call", category: "Repairs", default_rate: 220, pricing_display_type: "hourly_materials",
        default_description: "Nights, weekends and holidays. We answer the phone and get a plumber out for burst pipes, sewer backups and no-water calls." },
      { name: "Outdoor Faucet (Hose Bib) Replacement", category: "Installations", default_rate: 285, pricing_display_type: "starting_from",
        default_description: "Replace a leaking or frost-damaged outdoor faucet with a frost-free hose bib before freeze-up. Includes shutoff check." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "pool_service",
    label: "Pool Service",
    blurb: "Openings, closings and weekly water care.",
    services: [
      { name: "Pool Opening", category: "Openings & Closings", default_rate: 395, pricing_display_type: "starting_from",
        default_description: "Remove and store the winter cover, reinstall ladders and rails, start pump and filter, shock and balance the water. Startup chemicals included." },
      { name: "Pool Closing", category: "Openings & Closings", default_rate: 425, pricing_display_type: "starting_from",
        default_description: "Blow out and plug the lines, winterize pump, filter and heater, add closing chemicals, lower the water and install your cover." },
      { name: "Weekly Pool Maintenance", category: "Maintenance", default_rate: 85, pricing_display_type: "starting_from",
        default_description: "Weekly visit: skim, vacuum, brush the waterline, empty baskets, backwash as needed, test and balance the water. Chemicals billed as used." },
      { name: "Green Pool Recovery", category: "Maintenance", default_rate: 450, pricing_display_type: "starting_from",
        default_description: "Bring a green pool back to clear: heavy shock, repeat vacuuming and filter cleanings until it is swim-ready. Usually takes 3 to 5 visits." },
      { name: "Water Test & Balance Visit", category: "Maintenance", default_rate: 95, pricing_display_type: "starting_from",
        default_description: "One-time service call to test your water and adjust chlorine, pH, alkalinity and stabilizer. Chemicals used are billed at cost." },
      { name: "Filter Sand Change", category: "Maintenance", default_rate: 250, pricing_display_type: "starting_from_materials",
        default_description: "Remove old media, inspect laterals and internals, refill with new sand or glass media and restart the filter. Media billed separately." },
      { name: "Equipment Repair", category: "Repairs", default_rate: 115, pricing_display_type: "hourly_materials",
        default_description: "Diagnose and repair pumps, filters, heaters, chlorinators and pool plumbing. Parts billed separately. Most repairs finished in one visit." },
      { name: "Leak Detection", category: "Repairs", default_rate: 375, pricing_display_type: "starting_from",
        default_description: "Pressure test the plumbing and dye test fittings and the liner to locate the leak. You get written findings and a repair quote." },
      { name: "Pool Heater Installation", category: "Installations", default_rate: 700, pricing_display_type: "starting_from_materials",
        default_description: "Set the heater on its pad, plumb it in and run startup. Heater and parts billed separately. Gas hookup arranged with a licensed fitter." },
      { name: "Salt Water System Installation", category: "Installations", default_rate: 425, pricing_display_type: "starting_from_materials",
        default_description: "Install a salt chlorinator cell and controller on your existing plumbing and wiring, with the startup salt dose calculated for your pool." },
      { name: "Vinyl Liner Replacement", category: "Installations", default_rate: 5500, pricing_display_type: "starting_from",
        default_description: "Measure your pool, remove the old liner, repair minor wall and floor damage, install the new liner and manage the refill. Liner included." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
  {
    key: "roofing",
    label: "Roofing",
    blurb: "Repairs, replacements and roof inspections.",
    services: [
      { name: "Roof Leak Repair", category: "Repairs", default_rate: 475, pricing_display_type: "starting_from",
        default_description: "We track down the leak and repair shingles, sealant, and flashing in the affected area. Includes photos of the finished repair." },
      { name: "Asphalt Shingle Roof Replacement", category: "Installations", default_rate: 6.5, pricing_display_type: "per_sqft",
        default_description: "Full tear-off and re-shingle with architectural shingles, new underlayment, ice and water shield at the eaves, and haul-away of old material." },
      { name: "Chimney & Vent Flashing Repair", category: "Repairs", default_rate: 425, pricing_display_type: "starting_from",
        default_description: "Re-seal or replace flashing around chimneys, plumbing stacks, and vents. Common fix for leaks that show up on ceilings and walls." },
      { name: "Flat Roof Repair", category: "Repairs", default_rate: 650, pricing_display_type: "starting_from",
        default_description: "Patch repair for torch-on, EPDM, or TPO flat roofs. Includes membrane patch, seam sealing, and a check of nearby drains and flashing." },
      { name: "Roof Inspection & Report", category: "Maintenance", default_rate: 250, pricing_display_type: "starting_from",
        default_description: "Full walk-over of shingles, flashing, vents, and attic ventilation with a written report and photos. Fee waived if we do the repair." },
      { name: "Eavestrough Cleaning", category: "Maintenance", default_rate: 185, pricing_display_type: "starting_from",
        default_description: "Hand-clean all troughs and flush downspouts. We bag the debris and flag any loose hangers or slope problems while we are up there." },
      { name: "Eavestrough Installation", category: "Installations", default_rate: 14, pricing_display_type: "per_linear_ft",
        default_description: "5-inch seamless aluminum eavestrough with hangers and downspouts, colour-matched to your trim. Old troughs removed and disposed of." },
      { name: "Soffit & Fascia Repair", category: "Repairs", default_rate: 375, pricing_display_type: "starting_from",
        default_description: "Replace damaged soffit panels and cap rotted fascia in colour-matched aluminum. A common fix alongside eavestrough repairs." },
      { name: "Emergency Tarp & Leak Control", category: "Repairs", default_rate: 450, pricing_display_type: "starting_from",
        default_description: "Same-day tarp and temporary seal to stop active leaks after storm damage. Cost is credited toward the permanent repair." },
      { name: "Skylight Replacement", category: "Installations", default_rate: 850, pricing_display_type: "starting_from_materials",
        default_description: "Remove the old unit and install your new skylight with a fresh flashing kit and ice and water shield. Skylight quoted per manufacturer." },
      { name: "Metal Roof Installation", category: "Installations", default_rate: 12.5, pricing_display_type: "per_sqft",
        default_description: "Screw-down or standing seam metal panels over new underlayment. Final price depends on panel profile and roof complexity." },
      { name: "Roof Snow & Ice Dam Removal", category: "Maintenance", default_rate: 250, pricing_display_type: "hourly",
        default_description: "Winter roof snow clearing and ice dam steaming to prevent leaks and reduce load. Two-person crew working from ladders and roof anchors." },
    ],
    seasons: {},
    seasonalCampaigns: [],
    addons: [],
  },
]
