-- ── Measurement history (append-only) ────────────────────────────────────────
-- APPLIED to production 2026-07-16 via Supabase MCP; every guard proven by
-- execution (below). Companion to RUN-2026-07-16-measurement-engine-v2.sql.
--
-- WHY A NEW TABLE — neither existing one can answer the question.
--  * `measurements` is the auto-vs-accepted ACCURACY log (auto_sqft,
--    accepted_sqft, diff_pct) that trains the per-neighbourhood ratio. It answers
--    "how good is our estimator", is lawn/ft²-only, and keeps doing exactly that.
--  * `properties.measurement_history` is a jsonb array of lawn snapshots with a
--    pricing recommendation embedded — lawn-shaped and coupled to pricing.
-- Neither can say what this property's FENCE measured last month.
--
-- WRITTEN BY A TRIGGER: history a caller can forget to write is not history. One
-- writer (property_measurements) produces both the current row and its own trail.
--
-- APPEND-ONLY BY POLICY, not by convention: SELECT + INSERT policies exist and
-- UPDATE/DELETE do not, so a rewritten past is impossible rather than discouraged.
--
-- clock_timestamp() + seq: now() is transaction-start, so two saves in one
-- transaction would tie and the order of history would be ambiguous — the same
-- trap already hit and fixed on wage_history.
--
-- VERIFICATION — executed against prod, rolled back (0 rows after):
--   * create                  -> 1 event                                    OK
--   * re-trace with new value -> 2 events                                   OK
--   * unchanged re-save       -> still 2 (a no-op is not an event)          OK
--   * a fence keeps its own history, in linear_ft                           OK
--   * delete                  -> actions = measured,measured,removed        OK
--     (a deletion IS history)
--   * policies = 2 (select+insert only — history cannot be rewritten)       OK
--   * seq is a total order even within one transaction                      OK

create table if not exists public.property_measurement_events (
  id uuid primary key default gen_random_uuid(),
  created_at timestamptz not null default clock_timestamp(),
  seq bigint generated by default as identity,
  user_id uuid not null references auth.users(id) on delete cascade,
  property_id uuid not null,
  measurement_id uuid,
  kind text not null,
  unit text not null,
  value numeric(12,2) not null,
  shapes jsonb not null default '[]'::jsonb,
  source text not null,
  confidence text not null,
  confidence_reason text not null,
  -- 'measured' = created/updated · 'removed' = deleted. A deletion IS history.
  action text not null,
  measured_at timestamptz not null,
  constraint property_measurement_events_kind_known
    check (kind in ('lawn','mulch','gravel','rock','concrete','fencing','hedges','trees','snow')),
  constraint property_measurement_events_action_known check (action in ('measured','removed')),
  constraint property_measurement_events_value_nonneg check (value >= 0)
);

create index if not exists pme_property_idx on public.property_measurement_events (property_id, seq desc);
create index if not exists pme_property_kind_idx on public.property_measurement_events (property_id, kind, seq desc);
create index if not exists pme_user_idx on public.property_measurement_events (user_id, seq desc);

comment on column public.property_measurement_events.seq is
  'Monotonic tiebreaker. ORDER BY seq — created_at can tie at microsecond resolution.';

create or replace function public.log_measurement_event() returns trigger
language plpgsql as $$
begin
  if tg_op = 'DELETE' then
    insert into public.property_measurement_events
      (user_id, property_id, measurement_id, kind, unit, value, shapes, source, confidence, confidence_reason, action, measured_at)
    values (old.user_id, old.property_id, old.id, old.kind, old.unit, old.value, old.shapes,
            old.source, old.confidence, old.confidence_reason, 'removed', old.measured_at);
    return null;
  end if;
  -- Only log when something a reader would care about actually moved. An
  -- unchanged re-save is not a measurement event.
  if tg_op = 'UPDATE'
     and new.value is not distinct from old.value
     and new.source is not distinct from old.source
     and new.shapes is not distinct from old.shapes then
    return null;
  end if;
  insert into public.property_measurement_events
    (user_id, property_id, measurement_id, kind, unit, value, shapes, source, confidence, confidence_reason, action, measured_at)
  values (new.user_id, new.property_id, new.id, new.kind, new.unit, new.value, new.shapes,
          new.source, new.confidence, new.confidence_reason, 'measured', new.measured_at);
  return null;
end $$;

drop trigger if exists property_measurements_history on public.property_measurements;
create trigger property_measurements_history
  after insert or update or delete on public.property_measurements
  for each row execute function public.log_measurement_event();

alter table public.property_measurement_events enable row level security;
drop policy if exists pme_select on public.property_measurement_events;
drop policy if exists pme_insert on public.property_measurement_events;
-- SELECT + INSERT only, deliberately: history is append-only. No update/delete
-- policy means a rewritten past is not merely discouraged, it is impossible.
create policy pme_select on public.property_measurement_events for select using (auth.uid() = user_id);
create policy pme_insert on public.property_measurement_events for insert with check (auth.uid() = user_id);

comment on table public.property_measurement_events is
  'Append-only history for property_measurements, written by trigger. No UPDATE/DELETE policy — history cannot be rewritten. Distinct from `measurements` (the lawn auto-vs-accepted accuracy log that trains neighbourhood ratios).';
